---
# This file contains variables that should be shared across all devices

# Are there two routers?
dual_routers: False 
intra_router_interface: "GigabitEthernet0/2"

# Basic VRF variables
vrf_name: "guestVRF"
vrf_vlan: "1740"

# LAN Interface variables
lan_interface: "GigabitEthernet0/0/0"
fhrp_group: "780"
fhrp_gw_ip: "172.16.0.1"
lag_interface: "Port-channel1"

# Transport Uplink Variables
transport1_interface: "GigabitEthernet0/0"
transport1_vlan: "1741"
transport1_ip: "172.0.5.2"
transport1_mask: "255.255.255.252"

transport2_interface: "GigabitEthernet0/1"
transport2_vlan: "1742"
transport2_ip: "172.0.5.6"
transport2_mask: "255.255.255.252"

# OSPF Variables
ospf_vrf_area: "12345"
ospf:
  networks:
      # Add as many or few networks as desired 
    - { network: "172.16.0.0", wildcard_mask: "0.0.7.255", area: "{{ ospf_vrf_area }}" }
    #- { network: "172.0.5.0", wildcard_mask: "0.0.0.255", area: "0" }
