---

- name: Build 2911 Router VRF
  hosts: ios 
  connection: local
  gather_facts: no

  tasks:

  - name: BUILD CONFIGURATION
    template:
      src=templates/2911-router.j2
      dest=configs/{{ router_name }}.conf
    tags: build-2911
