- name: Build 2911 VRF Configurations
  hosts: 2911-routers
  connection: local
  gather_facts: no

  tasks:

  - name: BUILD 2911 Router Configuration
    template:
      src: templates/2911-router-base.j2
      dest: configs/{{ inventory_hostname }}-config.txt
      backup: yes
    tags: build-2911
