---
- name: Build 4500 VRF Configurations
  hosts: 4500-routers 
  connection: local
  gather_facts: no

  tasks:
  
  - name: Build 4500 Router Configurations
    template:
      src: templates/4500-router.j2
      dest: configs/{{ inventory_hostname }}-config.txt
      backup: yes
    tags: build-4500

- name: Build Core Router VRF Sub-Interface Configurations
  hosts: core-routers 
  connection: local
  gather_facts: no

  tasks:
  
  - name: Build Core Routers Configurations
    template:
      src: templates/core-routers.j2
      dest: configs/{{ inventory_hostname }}-config.txt
      backup: yes
    tags: build-cores

- name: Build Access-Switch VRF Configurations
  hosts: access-switches 
  connection: local
  gather_facts: no

  tasks:
  
  - name: Build Core Routers Configurations
    template:
      src: templates/access-switches.j2
      dest: configs/{{ inventory_hostname }}-config.txt
      backup: yes
    tags: build-access

#############################################################################

- name: Build 2911 VRF Configurations
  hosts: 2911-router
  connection: local
  gather_facts: no

  tasks:

  - name: BUILD 2911 Router Configuration
    template:
      src: templates/2911-router-base.j2
      dest: configs/{{ inventory_hostname }}-config.txt
      backup: yes
    tags: build-2911

