---

- name: Build VRF Configurations
  hosts: ios 
  connection: local
  gather_facts: no

  tasks:

  - name: BUILD 2911 Router Configuration
    template:
      src=templates/2911-router-base.j2
      dest=configs/{{ router_name }}.conf
    tags: build-2911
  
  - name: BUILD 4500 Router Configuration
    template:
      src=templates/4500-router-base.j2
      dest=configs/{{ router_name }}.conf
    tags: build-4500
