---
- name: NAPALM Merge Config
  hosts: A1106-DST-4K1 
  connection: local
  gather_facts: no
  
  tasks:
    - name: NAPALM Merge Config
      napalm_install_config:
        hostname: "{{ ansible_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        dev_os: "{{ os }}"
        optional_args:
          secret: "{{ distro_enable_secret }}"
        config_file: "configs/{{ inventory_hostname }}-config.txt"
        commit_changes: False     # Set to True to actually commit the changes. False means just get diffs
        diff_file: "diffs/{{ inventory_hostname }}-diff.txt"
        archive_file: "backups/{{ inventory_hostname }}-backup.txt"
      register: results
      tags: merge-config
      notify:
        - rename-and-copy-merged
        - delete-merged-config

  handlers:
    - name: rename-and-copy-merged
      copy:
        src:  "configs/{{ inventory_hostname }}-config.txt"
        dest: "merged-configs/{{ inventory_hostname }}-merged.txt"
    
    - name: delete-merged-config
      file:
        path: "configs/{{ inventory_hostname }}-config.txt"
        state: absent
