---
# Basic VRF Variables
vrf:
  name: guest_vrf
  vlan: 1740
vrf_trans1:
  vlan: 1741
  name: "TX-COR {{ vrf.name }} Transport"
vrf_trans2:
  vlan: 1742
  name: "OPS-COR {{ vrf.name }} Transport"
lag_interface:  # L2 interface between two 4500 routers
  name: Port-channel1

# Layer 3 Variables
L3:
  router1_ip: 10.174.68.2
  router2_ip: 10.174.68.3
  mask: 255.255.252.0
  helpers:
    # The following are guest helper addresses comment-out for other VRFs
    -  10.200.123.80
    -  10.3.122.23
    # The following are non-guest helpers uncomment as needed
    #-  10.200.112.125
    #-  10.3.112.126
  fhrp:
    type: hsrp
    ip: 10.174.68.1
    group: 1740
  trans1:
    name: TenGigabitEthernet1/3
    router1_ip: 10.175.254.238
    router2_ip: 10.175.255.74
  trans2:
    name: TenGigabitEthernet1/4
    router1_ip: 10.175.255.70
    router2_ip: 10.175.254.230
  trans_mask: 255.255.255.252

# Routing Variables. Specifically, OSPF
ospf_area: 17468
ospf_network: 10.174.68.0

# Ports to access switches
access_downlinks:
  ranges:
    - "TenGigabitEthernet1/6 - 13"
  # Add individual interfaces to list below if you need to add individual interfaces 
  # Example: [TenGigabitEthernet1/6, TenGigabitEthernet1/11]
  interfaces: []    
