---
# This file contains variables that should be shared across 2911 Routers 

# Basic VRF variables
vrf_name: "guestVRF"
vrf_vlan: "1740"

# For Two Router Deployments
intra_router:
  interface_1: { name: "GigabitEthernet0/2", ip: "192.168.1.1", peer: "router2" }
  interface_2: { name: "GigabitEthernet0/2", ip: "192.168.1.2", peer: "router1" }
  mask: "255.255.255.252"

# LAN Interface(s) variables
vrf_lan:
  interface_1: { name: "GigabitEthernet0/0/0", ip: "172.16.0.2" }
  interface_2: { name: "GigabitEthernet0/0/0", ip: "172.16.0.3" }    # Used in dual router deployments
  mask: "255.255.255.0"
  lag_interface: "Port-channel1"  # Normally used in single router deployments to access-switch
  fhrp_type: "glbp"
  fhrp_group: "780"
  fhrp_gw_ip: "172.16.0.1"
  ip_helpers:
    - 10.200.112.125
    - 10.200.123.26
    - 10.3.112.126

# Transport Uplink Variables
transports:
  interface_1: { name: "GigabitEthernet0/0", vlan: "1741", ip: "172.0.5.2", man_name: "T0150-MAN-75K1" }
  interface_2: { name: "GigabitEthernet0/1", vlan: "1742", ip: "172.0.5.6", man_name: "LAC-MAN-75K1" }
  mask: "255.255.255.252"

# OSPF Variables
ospf_vrf_area: "12345"
ospf:
  networks:
      # Add as many or few networks as desired 
    - { network: "172.16.0.0", wildcard_mask: "0.0.7.255", area: "{{ ospf_vrf_area }}" }
